const {chromium}=require('playwright-core'),binary=require('@sparticuz/chromium').default,fs=require('fs'),assert=require('assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:await binary.executablePath(),args:binary.args,headless:true});
 try{
 const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));let requests=[],rows=[];
 await page.addInitScript(()=>{window.Telegram={WebApp:{initData:'signed-test',initDataUnsafe:{user:{id:123}},ready(){},expand(){},enableClosingConfirmation(){},setHeaderColor(){},setBackgroundColor(){}}};localStorage.setItem('1shot_v2_profile',JSON.stringify({telegram_id:123,username:'Test',gizmo_user_id:7}))});
 await page.route('**/*',async route=>{
 const url=new URL(route.request().url());
 if(url.host==='club.test'){const file=url.pathname==='/'?'index.html':url.pathname.slice(1);if(fs.existsSync(file))return route.fulfill({contentType:file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.woff2')?'font/woff2':'text/html',body:fs.readFileSync(file)});}
 if(url.pathname.endsWith('/hosts'))return route.fulfill({contentType:'application/json',body:JSON.stringify({hosts:Array.from({length:31},(_,i)=>({host_id:String([11,12,13,14,15,21,22,23,24,25,101,102,103,104,105,106,201,202,203,204,205,206,207,208,301,302,303,304,401,402,1][i]),status:i===0?'busy':'free',updated_at:new Date().toISOString()}))})});
 if(url.pathname.endsWith('/club-bookings')){if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'*'}});const b=route.request().postDataJSON();requests.push(b);let res={};if(b.action==='capabilities')res={enabled:true};if(b.action==='list')res={bookings:rows};if(b.action==='create'){rows=[{id:'test-booking',host_id:b.host_id,mode:b.mode,duration_kind:b.duration_kind,starts_at:new Date().toISOString(),ends_at:new Date(Date.now()+3600000).toISOString(),hold_until:new Date(Date.now()+3600000).toISOString(),status:'holding'}];res={booking_id:'test-booking'}}if(b.action==='checkin')rows[0].status='checkin_pending';return route.fulfill({headers:{'Access-Control-Allow-Origin':'*'},contentType:'application/json',body:JSON.stringify(res)})}
 return route.abort();
 });
 await page.goto('https://club.test/');await page.waitForSelector('.map-pc.free');await page.waitForFunction(()=>window.clubV2===true);await page.waitForSelector('#splash',{state:'hidden'});
 for(const size of [{width:390,height:844},{width:320,height:568},{width:844,height:390}]){await page.setViewportSize(size);for(const zone of ['vip','standard']){await page.evaluate(z=>switchZone(z),zone);const sizes=await page.evaluate(()=>['app','hall-area','floor-map'].map(id=>{const e=document.getElementById(id);return [id,e.scrollHeight,e.clientHeight,e.scrollWidth,e.clientWidth]}));sizes.forEach(([id,h,ch,w,cw])=>assert.ok(h<=ch+1&&w<=cw+1,JSON.stringify({id,h,ch,w,cw})))}}
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>switchZone('vip'));await page.locator('[data-hid="11"]').click();await page.waitForSelector('#occupied-dialog[open]');await page.locator('#occupied-dialog button').click();await page.locator('[data-hid="12"]').click();await page.locator('[data-mode="scheduled"]').click();assert.equal(await page.locator('[data-mode="scheduled"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#club-hours [role=option]').count(),24);assert.equal(await page.locator('#club-minutes [role=option]').count(),12);
 await page.locator('#club-hours').focus();await page.keyboard.press('Home');await page.keyboard.press('ArrowDown');assert.match(await page.locator('#club-start').textContent(),/01:/);assert.equal(await page.locator('[data-kind]').count(),0);
 await page.locator('#club-submit').click();await page.waitForSelector('.club-reservation input');assert.equal(requests.filter(b=>b.action==='create').length,1);const created=requests.find(b=>b.action==='create');assert.equal(created.duration_kind,'range');assert.equal(Date.parse(created.ends_at)-Date.parse(created.starts_at),1800000);assert.equal(created.mode,'scheduled');assert.ok(created.client_request_id);assert.ok(!('gizmo_user_id' in created));
 await page.locator('.club-reservation input').fill('123456');await page.locator('.club-reservation .btn-main').click();await page.waitForFunction(()=>document.querySelector('#club-mine').textContent.includes('Выполняем вход'));assert.equal(requests.filter(b=>b.action==='checkin').length,1);assert.deepEqual(errors,[]);console.log('Club browser: opt-in, responsive layout, busy-PC rejection and free-PC scheduled mode, five-minute wheels, half-hour wait, booking, presence check-in passed.');
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});
