const {chromium}=require('playwright-core'),binary=require('@sparticuz/chromium').default,fs=require('fs'),assert=require('assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:await binary.executablePath(),args:binary.args,headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1120,height:760}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  await page.addInitScript(()=>{
   window.calls=[];window.resets=[{id:'r1',gizmo_user_id:7,telegram_id:123},{id:'r2',gizmo_user_id:8,telegram_id:124},{id:'r3',gizmo_user_id:9,telegram_id:125}];let rows=[{id:'b1',username:'guest',host_id:'14',mode:'arrival',duration_kind:'hour',status:'holding',protocol:2,starts_at:'2026-09-25T12:00:00Z',ends_at:'2026-09-25T13:00:00Z',hold_until:'2026-09-25T13:00:00Z'}];
   window.pywebview={api:{snapshot:async()=>({online:true,last_sync:Date.now()/1000,protocol_ready:true,rows,alerts:1,error:'',sync_error:'',hosts:[{host_id:'14',status:'reserved'}],password_requests:resets,sound:{preset:'soft',volume:50,repeat:20,enabled:true}}),cancel_booking:async id=>{calls.push(['cancel',id]);rows[0].status='cancel_requested';return {ok:true}},sound_settings:async s=>{calls.push(['sound',s]);return s},test_sound:async()=>calls.push(['test_sound']),booking_guest:async id=>({user:{username:'guest',firstName:'Андрей',mobilePhone:'+79991234567'},gizmo_user_id:7,telegram_id:123}),prepare_password_request:async id=>{calls.push(['prepare',id]);return {user:{id:7,username:'request_guest'}}},reset_password_request:async(id,username,password,confirmed)=>{calls.push(['request-reset',id,username,password.length,confirmed]);resets=resets.filter(r=>r.id!==id);return {ok:true,synced:true}},resolve_password_request:async(id,outcome,confirmed)=>{calls.push(['resolve',id,outcome,confirmed]);resets=resets.filter(r=>r.id!==id);return {ok:true,synced:true}},find_account:async username=>({user:{id:7,username,firstName:'Андрей'}}),reset_password:async(id,username,password)=>{calls.push(['reset',id,username,password.length]);return {ok:true}},close:async()=>calls.push(['close']),minimize:async()=>{},maximize:async()=>{},quit:async()=>{},acknowledge:async()=>{}}};
   document.addEventListener('DOMContentLoaded',()=>window.dispatchEvent(new Event('pywebviewready')));
  });
  await page.route('**/*',route=>{const url=new URL(route.request().url());if(url.host==='desk.test'){const file='desktop/'+(url.pathname==='/'?'index.html':url.pathname.slice(1));if(fs.existsSync(file))return route.fulfill({contentType:file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.woff2')?'font/woff2':file.endsWith('.svg')?'image/svg+xml':file.endsWith('.png')?'image/png':'text/html',body:fs.readFileSync(file)})}return route.abort()});
  await page.goto('https://desk.test/');await page.waitForSelector('.desk-pc');assert.equal(await page.locator('.desk-pc').count(),30);
  await page.waitForSelector('#desk-splash',{state:'detached'});await page.evaluate(()=>document.fonts.ready);assert.ok(await page.evaluate(()=>[...document.fonts].some(f=>f.family==='Unbounded'&&f.status==='loaded')));
  await page.setViewportSize({width:900,height:600});assert.ok(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight));assert.equal(await page.locator('footer').count(),0);await page.locator('.desk-pc.reserved').click();await page.locator('.guest-details summary').click();await page.waitForFunction(()=>document.querySelector('.guest-details').textContent.includes('+79991234567'));await page.getByRole('button',{name:'Отменить бронь',exact:true}).click();assert.deepEqual(await page.evaluate(()=>calls.find(c=>c[0]==='cancel')),['cancel','b1']);
  await page.locator('[data-panel="sound"]').click();await page.locator('#sound-preset').selectOption('chime');await page.locator('#sound-volume').fill('25');await page.getByRole('button',{name:'Сохранить и проверить'}).click();assert.equal(await page.evaluate(()=>calls.find(c=>c[0]==='sound')[1].volume),25);
  await page.locator('[data-panel="accounts"]').click();await page.locator('#account-search').fill('guest');await page.getByRole('button',{name:'Найти аккаунт'}).click();await page.waitForSelector('#reset-user:not([hidden])');await page.locator('#new-password').fill('test-password');await page.locator('#identity-checked').check();await page.getByRole('button',{name:'Установить новый пароль'}).click();await page.waitForFunction(()=>document.querySelector('#account-message').textContent.includes('изменён'));assert.equal(await page.locator('#new-password').inputValue(),'');
  await page.getByRole('button',{name:'Сменить пароль',exact:true}).first().click();assert.equal(await page.locator('#identity-checked').isChecked(),false);await page.locator('#new-password').fill('request-password');await page.locator('#identity-checked').check();await page.getByRole('button',{name:'Установить новый пароль'}).click();await page.waitForFunction(()=>calls.some(c=>c[0]==='request-reset'));assert.deepEqual(await page.evaluate(()=>calls.find(c=>c[0]==='request-reset')),['request-reset','r1','request_guest',16,true]);
  await page.getByRole('button',{name:'Услуга предоставлена',exact:true}).first().click();await page.getByRole('button',{name:'Закрыть без выполнения',exact:true}).first().click();assert.deepEqual(await page.evaluate(()=>calls.filter(c=>c[0]==='resolve')),[['resolve','r2','done',true],['resolve','r3','rejected',true]]);assert.equal(await page.locator('.reset-request').count(),0);
  await page.locator('[aria-label="Скрыть в трей"]').click();assert.ok(await page.evaluate(()=>calls.some(c=>c[0]==='close')));assert.deepEqual(errors,[]);
  console.log('Desk UI passed: local Unbounded, 30-PC map, admin cancellation, sound settings, verified account reset UI, custom window controls.');
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});
