import {PGlite} from 'npm:@electric-sql/pglite@0.3.14';
import {createHmac,createHash,createDecipheriv} from 'node:crypto';
import {configureDatabase} from '../server/database.ts';
import auth from '../server/routes/club-auth.ts';
import desk from '../server/routes/club-desk.ts';
import bookings from '../server/routes/club-bookings.ts';
const assert=(v:unknown,m='assertion failed')=>{if(!v)throw Error(m)};
Deno.test('guest-selected password: scoped authorization, ownership, encryption, expiry, claim-once and verified completion',async()=>{
 const pg=new PGlite(),worker=crypto.randomUUID(),source=crypto.randomUUID(),token='123:fixture',secret='fixture-secret';
 Deno.env.set('AGENT_SECRET',secret);Deno.env.set('TELEGRAM_BOT_TOKEN',token);
 try{
  await pg.exec(await Deno.readTextFile('server/sql/base.sql'));
  for(const f of (await Array.fromAsync(Deno.readDir('supabase/migrations'))).map(x=>x.name).sort().filter(x=>/2026092500(06|07|08|09|10|11|12)_|2026100800(14|15|16)_/.test(x)))await pg.exec(await Deno.readTextFile('supabase/migrations/'+f));
  configureDatabase(async(q,args)=>(await pg.query(q,args)).rows as any[]);
  await pg.query('select club_worker_poll($1)',[worker]);await pg.exec("update club_settings set enabled=true,flow_version=2;insert into profiles(telegram_id,gizmo_user_id,username) values(100,7,'guest'),(101,8,'other')");
  await pg.query("insert into club_commands(id,telegram_id,gizmo_user_id,kind,status,request_id) values($1,100,7,'password_request','awaiting_admin',gen_random_uuid())",[source]);
  const signed=(id:number)=>{const p=new URLSearchParams({auth_date:String(Math.floor(Date.now()/1000)),user:JSON.stringify({id})});const check=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>k+'='+v).join('\n');p.set('hash',createHmac('sha256',createHmac('sha256','WebAppData').update(token).digest()).update(check).digest('hex'));return p.toString()};
  const call=async(handler:typeof auth,b:unknown,staff=false)=>{const r=await handler(new Request('http://test',{method:'POST',headers:{'Content-Type':'application/json',...(staff?{'x-agent-secret':secret}:{})},body:JSON.stringify(b)}));return {status:r.status,data:await r.json()}};
  const authorization={action:'password_authorize',worker_id:worker,source:'password_request',id:source,gizmo_user_id:7,username:'guest',group_id:3,minimum_length:1,confirmed:true,privileged:false};
  assert((await call(desk,authorization)).status===403);assert((await call(desk,{...authorization,confirmed:false},true)).status===409);
  assert((await call(desk,{...authorization,gizmo_user_id:8},true)).status===409);
  const granted=await call(desk,authorization,true);assert(granted.status===200,JSON.stringify(granted));const id=granted.data.data;
  assert((await call(desk,authorization,true)).data.data===id,'authorization retry does not extend or duplicate grant');
  const request=crypto.randomUUID(),submit={action:'password_submit',grant_id:id,request_id:request,password:'x',initData:signed(100)};
  assert((await call(auth,{...submit,initData:signed(101)})).status===429,'other owner denied');
  assert((await call(auth,{...submit,password:' '})).status===400);
  assert((await call(auth,{...submit,grant_id:id.toUpperCase(),request_id:request.toUpperCase()})).data.status==='queued');
  assert((await call(auth,submit)).data.status==='queued');
  assert((await call(auth,{...submit,request_id:crypto.randomUUID(),password:'different'})).status===429,'credential replacement refused');
  const owner=await call(bookings,{action:'capabilities',recovery_pending:true,initData:signed(100)});assert(owner.data.password_grant.id===id);assert(!JSON.stringify(owner).includes('cipher'));
  assert((await call(bookings,{action:'capabilities',recovery_pending:true,initData:signed(101)})).data.password_grant===null);
  const packet=(await pg.query<any>('select club_worker_poll($1) as r',[worker])).rows[0].r;assert(packet.desk.password_grants[0].id===id);assert(!JSON.stringify(packet).includes('cipher'));
  const claim=await call(desk,{action:'password_claim',worker_id:worker,id},true);assert(claim.status===200,JSON.stringify(claim));const row=claim.data.data;
  const bytes=Uint8Array.from(atob(row.cipher),c=>c.charCodeAt(0)),cipher=createDecipheriv('aes-256-gcm',createHash('sha256').update('1shot-password-v1:'+secret).digest(),bytes.slice(0,12));cipher.setAAD(new TextEncoder().encode(id+':'+request));cipher.setAuthTag(bytes.slice(-16));assert(JSON.parse(cipher.update(bytes.slice(12,-16)).toString()+cipher.final().toString()).password==='x');
  assert((await call(desk,{action:'password_claim',worker_id:worker,id},true)).status===409);
  assert((await pg.query<any>('select cipher,status from club_password_grants where id=$1',[id])).rows[0].cipher===null);
  const finish={action:'password_finish',worker_id:worker,id,status:'done'};assert((await call(desk,finish,true)).data.ok);assert((await call(desk,finish,true)).data.ok);
  assert((await pg.query<any>('select status from club_commands where id=$1',[source])).rows[0].status==='done');
  assert((await call(auth,{...submit,request_id:crypto.randomUUID()})).status===429,'completed grant cannot be reused');
  await pg.query("update club_commands set status='awaiting_admin' where id=$1",[source]);
  const second=(await call(desk,{...authorization,minimum_length:8,privileged:true},true)).data.data;
  assert((await call(auth,{...submit,grant_id:second,request_id:crypto.randomUUID()})).status===429,'staff minimum eight');
  await pg.query("update club_password_grants set expires_at=now()-interval '1 second' where id=$1",[second]);
  assert((await call(auth,{...submit,grant_id:second,password:'long-enough',request_id:crypto.randomUUID()})).status===429);
  assert((await call(bookings,{action:'capabilities',recovery_pending:true,initData:signed(100)})).data.password_grant.status==='expired');
  const third=(await call(desk,authorization,true)).data.data;
  await call(auth,{...submit,grant_id:third,request_id:crypto.randomUUID()});await call(desk,{action:'password_claim',worker_id:worker,id:third},true);
  await call(desk,{action:'password_finish',worker_id:worker,id:third,status:'attention'},true);
  assert((await call(desk,{action:'password_review',worker_id:worker,id:third},true)).status===409,'phone or known UID is not access proof');
  const proof=crypto.randomUUID();await pg.query("insert into club_auth_requests(id,telegram_id,gizmo_user_id,status,purpose) values($1,100,7,'done','login')",[proof]);
  assert((await call(desk,{action:'password_review',worker_id:worker,id:third},true)).data.data.proof_id===proof);
  const resolve={action:'password_resolve',worker_id:worker,id:third,proof_id:proof,confirmed:true};
  assert((await call(desk,{...resolve,confirmed:false},true)).status===409);assert((await call(desk,resolve,true)).data.ok);assert((await call(desk,resolve,true)).data.ok);
  assert((await pg.query<any>('select status from club_password_grants where id=$1',[third])).rows[0].status==='resolved','access is not reported as verified password change');
  await pg.query("update club_commands set status='awaiting_admin' where id=$1",[source]);
  const fourth=(await call(desk,authorization,true)).data.data;
  await call(auth,{...submit,grant_id:fourth,request_id:crypto.randomUUID()});await pg.exec('update profiles set gizmo_user_id=8 where telegram_id=100');
  assert((await call(desk,{action:'password_claim',worker_id:worker,id:fourth},true)).status===409,'changed owner link invalidates claim');
  await pg.exec('set role anon');let denied=false;try{await pg.query('select club_password_status(100)')}catch{denied=true}assert(denied);
 }finally{await pg.close()}
});
