import {PGlite} from 'npm:@electric-sql/pglite@0.3.14';
import {createHmac,createDecipheriv,createHash} from 'node:crypto';
import {configureDatabase} from '../server/database.ts';
import auth from '../server/routes/club-auth.ts';
import desk from '../server/routes/club-desk.ts';
import bookings from '../server/routes/club-bookings.ts';
const assert=(v:unknown,message='assertion failed')=>{if(!v)throw Error(message)};
Deno.test('registration: private queue, owner status, single confirmed claim, encrypted password, atomic link and no replay',async()=>{
 const pg=new PGlite(),secret='fixture-secret',token='123:fixture-token',worker=crypto.randomUUID();
 Deno.env.set('AGENT_SECRET',secret);Deno.env.set('TELEGRAM_BOT_TOKEN',token);
 try{
  await pg.exec(await Deno.readTextFile('server/sql/base.sql'));
  for(const f of (await Array.fromAsync(Deno.readDir('supabase/migrations'))).map(x=>x.name).sort().filter(x=>/2026092500(06|07|08|09|10|11|12)_|202610080014_/.test(x)))await pg.exec(await Deno.readTextFile('supabase/migrations/'+f));
  configureDatabase(async(q,args)=>(await pg.query(q,args)).rows as any[]);
  const signed=(id:number)=>{const p=new URLSearchParams({auth_date:String(Math.floor(Date.now()/1000)),user:JSON.stringify({id})});const check=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>k+'='+v).join('\n');p.set('hash',createHmac('sha256',createHmac('sha256','WebAppData').update(token).digest()).update(check).digest('hex'));return p.toString()};
  const call=async(handler:typeof auth,body:unknown,staff=false)=>{const r=await handler(new Request('http://test',{method:'POST',headers:{'Content-Type':'application/json',...(staff?{'x-agent-secret':secret}:{})},body:JSON.stringify(body)}));return {status:r.status,data:await r.json()}};
  const application={action:'register_application',initData:signed(100),username:'guest_new',password:'x',first_name:'Test',last_name:'Guest',mobile_phone:'+79991234567',birth_date:'2000-01-01',sex:1};
  assert((await call(auth,{...application,action:'register'})).status===409);
  assert((await call(auth,{...application,password:' '})).status===400);
  const submitted=await call(auth,application);assert(submitted.status===200,JSON.stringify(submitted));const id=submitted.data.request_id;
  assert((await call(auth,application)).data.request_id===id,'resubmission does not change credentials or identity');
  assert((await pg.query<any>('select count(*) as n from profiles')).rows[0].n===0,'submission creates no profile');
  assert((await pg.query<any>('select count(*) as n from club_auth_requests')).rows[0].n===0,'old workers cannot claim registration');
  assert((await call(auth,{action:'registration_status',initData:signed(101)})).data.registration===null);
  const state=await call(bookings,{action:'capabilities',initData:signed(100),registration_pending:true});assert(state.data.registration.status==='awaiting_admin');assert(!JSON.stringify(state).includes('cipher'));
  assert((await call(bookings,{action:'capabilities',registration_pending:true,initData:'wrong'})).status===403);
  const poll=(await pg.query<any>('select club_worker_poll($1) as value',[worker])).rows[0].value;assert(poll.desk.registrations.length===1);assert(!JSON.stringify(poll).includes('cipher'));assert(!('password' in poll.desk.registrations[0].public_data));
  assert((await call(desk,{action:'registration_claim',worker_id:worker,id},true)).status===409);
  assert((await call(desk,{action:'registration_claim',worker_id:worker,id,confirmed:true})).status===403);
  const claimed=await call(desk,{action:'registration_claim',worker_id:worker,id,confirmed:true},true);assert(claimed.status===200,JSON.stringify(claimed));
  const bytes=Uint8Array.from(atob(claimed.data.request.cipher),c=>c.charCodeAt(0)),decrypt=createDecipheriv('aes-256-gcm',createHash('sha256').update('1shot-auth-v2:'+secret).digest(),bytes.slice(0,12));decrypt.setAAD(new TextEncoder().encode(id));decrypt.setAuthTag(bytes.slice(-16));const plaintext=decrypt.update(bytes.slice(12,-16)).toString()+decrypt.final().toString();assert(JSON.parse(plaintext).password==='x');
  assert((await pg.query<any>('select cipher from club_registration_requests where id=$1',[id])).rows[0].cipher===null);
  assert((await call(desk,{action:'registration_claim',worker_id:worker,id,confirmed:true},true)).status===409);
  const finish={action:'registration_finish',worker_id:worker,id,status:'done',gizmo_user_id:7};assert((await call(desk,finish,true)).data.ok);assert((await call(desk,finish,true)).data.ok);
  const done=(await call(auth,{action:'registration_status',initData:signed(100)})).data.registration;assert(done.status==='done'&&done.profile.gizmo_user_id===7);
  assert((await pg.query<any>('select public_data from club_registration_requests where id=$1',[id])).rows[0].public_data.username===undefined);
  assert((await call(auth,{...application,initData:signed(100)})).status===429,'linked accounts cannot re-register');
  const second=(await call(auth,{...application,initData:signed(102)})).data.request_id;await pg.query("update club_registration_requests set expires_at=now()-interval '1 second' where id=$1",[second]);
  assert((await call(auth,{action:'registration_status',initData:signed(102)})).data.registration.status==='expired');
  assert((await pg.query<any>('select cipher,public_data from club_registration_requests where id=$1',[second])).rows[0].cipher===null);
  const third=(await call(auth,{...application,initData:signed(103)})).data.request_id;
  await call(desk,{action:'registration_claim',worker_id:worker,id:third,confirmed:true},true);
  await pg.query("update club_registration_requests set updated_at=now()-interval '16 minutes' where id=$1",[third]);
  assert((await call(auth,{action:'registration_status',initData:signed(103)})).data.registration.status==='attention');
  assert((await call(auth,{...application,initData:signed(103)})).data.request_id===third,'attention blocks new creation');
  assert((await call(desk,{...finish,id:third},true)).data.ok===false,'late completion needs reconciliation');
  const fourth=(await call(auth,{...application,initData:signed(104)})).data.request_id;
  await call(desk,{action:'registration_claim',worker_id:worker,id:fourth,confirmed:true},true);
  await pg.query("insert into profiles(telegram_id,gizmo_user_id,username) values(104,99,'existing')");
  assert((await call(desk,{...finish,id:fourth},true)).status===409,'never overwrite a concurrent login link');
  assert((await pg.query<any>('select gizmo_user_id from profiles where telegram_id=104')).rows[0].gizmo_user_id===99);
  const fifth=(await call(auth,{...application,initData:signed(105)})).data.request_id;
  assert((await call(desk,{action:'registration_reject',worker_id:worker,id:fifth,confirmed:true},true)).data.ok);
  assert((await call(desk,{action:'registration_claim',worker_id:worker,id:fifth,confirmed:true},true)).status===409);
  await pg.query("update club_worker set lease_until=now()-interval '1 second'");
  assert((await call(desk,finish,true)).status===409,'expired workers cannot report');
  await pg.exec('set role anon');let blocked=false;try{await pg.query('select club_registration_status(100)')}catch{blocked=true}assert(blocked,'anon cannot call privileged RPC');
 }finally{await pg.close()}
});
