"""Run before packaging: python -m desktop.write_metadata."""
import json
import shutil
from pathlib import Path
from .version import VERSION, VERSION_INFO, AUTHOR, APP_TITLE

def main():
    root=Path(__file__).resolve().parent
    shutil.copytree(root.parent/'assets/fonts',root/'assets/fonts',dirs_exist_ok=True)
    shutil.copyfile(root.parent/'hall-map.js',root/'assets/hall-map.js')
    (root/'brand.js').write_text('window.DESK_BUILD = '+json.dumps(dict(version=VERSION,author=AUTHOR,title=APP_TITLE),ensure_ascii=False)+';\n',encoding='utf-8')
    strings={'CompanyName':'tengizka','FileDescription':'1SHOT Club Desk','FileVersion':VERSION,
             'InternalName':'1SHOT-Desk','OriginalFilename':'1SHOT-Desk.exe',
             'ProductName':'1SHOT Club Desk','ProductVersion':VERSION,'Comments':AUTHOR}
    entries=',\n'.join(f'        StringStruct({k!r}, {v!r})' for k,v in strings.items())
    (root/'version-info.txt').write_text(f'''# Generated by desktop.write_metadata; edit desktop/version.py instead.
VSVersionInfo(
  ffi=FixedFileInfo(filevers={VERSION_INFO!r}, prodvers={VERSION_INFO!r},
    mask=0x3f, flags=0x2, OS=0x40004, fileType=0x1, subtype=0x0, date=(0,0)),
  kids=[StringFileInfo([StringTable('040904B0', [
{entries}
  ])]), VarFileInfo([VarStruct('Translation', [1033,1200])])]
)
''',encoding='utf-8')

if __name__=='__main__':main()
